runtime: nodejs8
threadsafe: true  # send more than one concurrent request at a time

handlers:
- url: /.*
  script: server.js

env_variables:
  MYSQL_URL: mysql://hubot:hubot-has-a-long-password@mysql/hubot
  HUBOT_SLACK_TOKEN: xoxb-8140795974-MdgmrcdrK0XwOSrh4G5ETTiA
  MYSQL_TABLE: brain
  NODE_IP: 0.0.0.0
  NODE_PORT: 8080
