// Generated by CoffeeScript 1.6.3
(function() {
  var helpContents;

  helpContents = function(name, commands) {
    return "<!DOCTYPE html>\n<html>\n  <head>\n  <meta charset=\"utf-8\">\n  <title>" + name + " Help</title>\n  <style type=\"text/css\">\n    body {\n      background: #d3d6d9;\n      color: #636c75;\n      text-shadow: 0 1px 1px rgba(255, 255, 255, .5);\n      font-family: Helvetica, Arial, sans-serif;\n    }\n    h1 {\n      margin: 8px 0;\n      padding: 0;\n    }\n    .commands {\n      font-size: 13px;\n    }\n    p {\n      border-bottom: 1px solid #eee;\n      margin: 6px 0 0 0;\n      padding-bottom: 5px;\n    }\n    p:last-child {\n      border: 0;\n    }\n  </style>\n  </head>\n  <body>\n    <h1>" + name + " Help</h1>\n    <div class=\"commands\">\n      " + commands + "\n    </div>\n  </body>\n</html>";
  };

  module.exports = function(robot) {
    robot.respond(/help\s*(.*)?$/i, function(msg) {
      var cmds, emit, filter, prefix;
      cmds = robot.helpCommands();
      filter = msg.match[1];
      if (filter) {
        cmds = cmds.filter(function(cmd) {
          return cmd.match(new RegExp(filter, 'i'));
        });
        if (cmds.length === 0) {
          msg.send("No available commands match " + filter);
          return;
        }
      }
      prefix = robot.alias || robot.name;
      cmds = cmds.map(function(cmd) {
        cmd = cmd.replace(/^hubot/, prefix);
        return cmd.replace(/hubot/ig, robot.name);
      });
      emit = cmds.join("\n");
      return msg.send(emit);
    });
    return robot.router.get("/" + robot.name + "/help", function(req, res) {
      var cmds, emit;
      cmds = robot.helpCommands().map(function(cmd) {
        return cmd.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
      });
      emit = "<p>" + (cmds.join('</p><p>')) + "</p>";
      emit = emit.replace(/hubot/ig, "<b>" + robot.name + "</b>");
      res.setHeader('content-type', 'text/html');
      return res.end(helpContents(robot.name, emit));
    });
  };

}).call(this);
