// Generated by CoffeeScript 1.6.3
(function() {
  var spawn;

  spawn = require('child_process').spawn;

  module.exports = function(robot) {
    robot.router.get("/hubot/version", function(req, res) {
      return res.end(robot.version);
    });
    robot.router.post("/hubot/ping", function(req, res) {
      return res.end("PONG");
    });
    robot.router.get("/hubot/time", function(req, res) {
      return res.end("Server time is: " + (new Date()));
    });
    robot.router.get("/hubot/info", function(req, res) {
      var child;
      child = spawn('/bin/sh', ['-c', "echo I\\'m $LOGNAME@$(hostname):$(pwd) \\($(git rev-parse HEAD)\\)"]);
      return child.stdout.on('data', function(data) {
        res.end("" + (data.toString().trim()) + " running node " + process.version + " [pid: " + process.pid + "]");
        return child.stdin.end();
      });
    });
    return robot.router.get("/hubot/ip", function(req, res) {
      return robot.http('http://ifconfig.me/ip').get()(function(err, r, body) {
        return res.end(body);
      });
    });
  };

}).call(this);
